(def #'node-require #'node:require)
(load "doqu.lisp")
;(load "html.lisp")
(def #'defnode #'doqu-define-node)
;(def #'deftemplate #'doqu-define-template)
;(def #'attribute #'doqu-render-linked-nodes)
(load "content.lisp")
;(load "template.lisp")
;(load "site.lisp")
;(doqu-render-site qua-lang)
