(load "lisp/doqu.lisp")
(load "lisp/html.lisp")
(def #'defnode #'doqu-define-node)
(def #'node-link #'doqu-node-link)
(def #'attribute #'doqu-attribute)
(load "lisp/content.lisp")
(load "lisp/template.lisp")
(load "lisp/site.lisp")
