(file "index.html" qua-hub-index qua-hub-template-large)
(file "intro.html" qua-hub-intro qua-hub-page-template-large)
(file "alpha.html" qua-hub-alpha qua-hub-page-template-large)
(file "manual.html" qua-hub-manual qua-hub-manual-template-large)
(file "usage.html" qua-hub-usage qua-hub-page-template-large)
