(file '(index) qua-hub-template-large)
(file '(intro) qua-hub-page-template-large)
(file '(alpha) qua-hub-page-template-large)
(file '(manual) qua-hub-manual-template-large)
(file '(usage) qua-hub-page-template-large)
